# Generated by Django 3.0.2 on 2020-01-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('type', models.IntegerField(choices=[(0, 'Приветствие нового пользователя')], primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
