version: '3'

services:
  redis:
    image: "redis:alpine"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - celery_beat
      - bot

  bot:
    build: .
    command: python manage.py bot_updater
    env_file:
      - .env

  celery:
    build: .
    command: celery -A bookclub worker -l info
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A bookclub beat -l info -S django
    env_file:
      - .env
    depends_on:
      - redis